version: "3.8"

services:
  tests:
    build: .
    environment:
      - BASE_URL=https://www.saucedemo.com/v1/
      - USERNAME_TEST=standard_user
      - PASSWORD=secret_sauce
    command: npx playwright test
    volumes:
      - .:/app